### ISSUE TITLE
Add to Intake known drivers?

### ISSUE THREAD

**Issue by martindurant** [NCAR/intake-cmip#12]
The page at https://intake.readthedocs.io/en/latest/plugin-directory.html lists drivers for Intake. Is this project ready to be included in the list? Perhaps I could prevail on you to write a blog article describing your use case and the development of this code?

Is there a recommended installation method yet? I have been slowly moving the most prominent intake packages over to conda-forge for the long-term.

**Comment by andersy005** [comment]
@martindurant, thank you for the pointer to the list of drivers for intake. I will definitely add intake-cmip to the list.

Regarding the installation, yesterday, I submitted a PR to conda-forge. Once this is approved, users will be able to install `intake-cmip` from conda-forge channel.

**Comment by martindurant** [comment]
Glad to hear it on both points! Feel free to close this issue.

**Comment by martindurant** [comment]
xref: https://github.com/ContinuumIO/intake/pull/223
